# Generated by Django 4.1.6 on 2023-05-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
